# Generated by Django 4.1.5 on 2023-05-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('sadness', models.FloatField()),
                ('joy', models.FloatField()),
                ('anger', models.FloatField()),
                ('love', models.FloatField()),
                ('surprise', models.FloatField()),
                ('fear', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Emotion Data',
            },
        ),
        migrations.AlterModelOptions(
            name='countrydata',
            options={'verbose_name_plural': 'Country Population Data'},
        ),
    ]
